FROM node:16-alpine

WORKDIR /app

# Install nodemon globally
RUN npm install -g nodemon

COPY backend/package*.json ./

RUN npm install

COPY backend/ .

EXPOSE 5000

# Use nodemon for development
CMD ["nodemon", "src/server.js"] 